Location:
  destination: /mnt/researchsan02a/Metadata_Processing/ECHO_PI-CHARM_demographic_feed
  source_dir: eval!os.environ.get('APP_MNT_BOX') + '/Navy_Charm_Meta_Data/demography/' # /home/stas/mnt/box/Navy_Charm_Meta_Data/demography
  source_file: CHARM age_sex*_updated.xlsx
Monitoring:
  action: copy
  # email_cc:
  # email_notification: true
  frequency: 60 # minimum delay between retrieval attempts (in seconds)
  item: file
  type: time_stamp
