Location:
  destination: D:\MounSinai\Darpa\Programming\monitor_files\data_file_examples\\target
  source_dir: D:\MounSinai\Darpa\Programming\monitor_files\data_file_examples\source\demographic_file\
  source_file: CHARM age_sex*_updated.xlsx
Monitoring:
  action: copy
  email_cc: null
  email_notification: true
  frequency: 60
  item: file
  type: time_stamp
